@startuml

!theme cerulean-outline

left to right direction

skinparam backgroundcolor White
skinparam component {
    backgroundColor<<user defined>> LightGray
}


database "Topic/Channels" {
    component MAILCHIMP_PROCESSING_FLOW_ID_INPUT<<PUB/SUB>>[
        MAILCHIMP_PROCESSING_FLOW_ID_INPUT
        --
        (MailChimpMessage)
    ]

}

component "MessageProcessingFlow" {
    [endpointPersister]
    [messagePersister]
    [mailchimpMessageSender]    

    endpointPersister -l-> messagePersister: (MailChimpMessage)
    messagePersister -l-> mailchimpMessageSender: (MailChimpMessage)
    endpointPersister ..> MAILCHIMP_PROCESSING_FLOW_ID_INPUT : (MailChimpMessage) 

}


@enduml