version: '3'

services:
  nc-postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: nc
      POSTGRES_USER: nc
      POSTGRES_PASSWORD: ZMss4o9mdBLV
    expose:
      - 5432
    ports:
      - 5432:5432
