image: gradle:6.8.2

definitions: 
   steps:
     - step: &runTestStep
         name: Run tests
         caches:
           - gradle
           - maven
           - docker
         services:
           - postgres
         script:
           - gradle :functions:simpleTest :functions:complexTest :osk-flows:simpleTest :osk-flows:complexTest -Dspring.profiles.active=bitbucket --stacktrace --info
         after-script:
           - pipe: atlassian/checkstyle-report:0.2.0
         artifacts: 
           - osk-flows/build/reports/tests/**
           - functions/build/reports/tests/**
   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'

pipelines:
  branches: 
    develop:
      - step: *runTestStep
    master:
      - step: *runTestStep
      - parallel:
         - step:
             name: Build FAT Jar
             script:
               - gradle build -x test --stacktrace --info   
             artifacts:
               - osk-flows/dist/**      
          
