image: gradle:6.8.2

definitions: 
   steps:
     - step: &runTestStep
         name: Run tests
         caches:
           - gradle
           - maven
           - docker
         services:
           - postgres
         script:
           - gradle :functions:simpleTest :functions:complexTest :osk-flows:simpleTest :osk-flows:complexTest -Dspring.profiles.active=bitbucket --stacktrace --info
         after-script:
           - pipe: atlassian/checkstyle-report:0.2.0
         artifacts: 
           - osk-flows/build/reports/tests/**
           - functions/build/reports/tests/**
   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'

pipelines:
  branches: 
    develop:
      - step: *runTestStep
    master:
      - step: *runTestStep
    release/*:
      - step: *runTestStep
  tags:
    v*:
      - step:
          name: Build FAT Jar
          caches:
           - gradle
           - maven
          script:
            - gradle build -x test --stacktrace --info   
          artifacts:
            - osk-flows/dist/**
      - step:
          name: Deploy to Bitbucket downloads
          script:
            - mv osk-flows/dist/osk-flows-1.0.0.jar osk-flows/dist/osk-flows-$BITBUCKET_TAG.jar 
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "osk-flows/dist/*.jar"
          
