image: gradle:6.8.2

definitions: 
   steps:
     - step: &test
         name: 'Run tests'
         script:
           - gradle test -Dspring.profiles.active=bitbucket --stacktrace --info
         services:
           - postgres
         caches:
           - gradle
         artifacts:
           - ./**/build/reports/tests/test/**

     - step: &release-nexus
         name: 'Release artifacts to https://infra.objectify.sk/maven/#browse/browse:maven-releases:objectify'
         script:
           - gradle publish --stacktrace --info
         caches:
           - gradle

   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - git push --mirror git@github.com:com-obj/notiflow.git
  branches:
    master:
      - step: *release-nexus # publication of SNAPSHOT release
    develop:
      - step: *test
    release/*:
      - step: *release-nexus # publication of SNAPSHOT release
    hotfix/*:
      - step: *release-nexus # publication of SNAPSHOT release      
  tags:
    v*:
      - step: *release-nexus # publication of FINAL release