#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:6.8.2

runTestsStep: &runTestStep 
  step:
    name: Run tests
    caches:
      - gradle
      - maven
      - docker
    services:
      - postgres
    script:
      - gradle test -Dspring.profiles.active=bitbucket --stacktrace
    after-script:
      - pipe: atlassian/checkstyle-report:0.2.0
    artifacts: 
#     - ./**/dist/**
      - ./**/build/reports/tests/test/**

pipelines:
  branches: 
    - master:
      - <<: *runTestStep
#      - step:
#          name: Security Scan
#          script:
#            # Run a security scan for sensitive data.
#            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
#            - pipe: atlassian/git-secrets-scan:0.4.3

          
definitions: 
   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'