image: gradle:6.8.2

runTestsStep: &runTestStep 
  step:
    name: Run tests
    caches:
      - gradle
      - maven
      - docker
    services:
      - postgres
    script:
      - gradle test -Dspring.profiles.active=bitbucket --stacktrace
    after-script:
      - pipe: atlassian/checkstyle-report:0.2.0
#    artifacts: 
#      - ./**/build/reports/tests/test/**

pipelines:
  branches: 
    develop:
      - <<: *runTestStep
    master:
      - <<: *runTestStep
      - parallel:
         - step:
             name: Build FAT Jar
             script:
               - pipe: atlassian/git-secrets-scan:0.4.3   
             astifacts:
               - ./**/dist/**   
         - step:
             name: Security Scan
             script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.        
          
definitions: 
   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'