image: gradle:6.8.2

options:
  docker: true

definitions: 
   steps:
     - run-tests: &run-tests
       - step: 
           name: Run tests
           caches:
             - gradle
             - maven
             - docker
           services:
             - postgres
           script:
             - gradle test -Dspring.profiles.active=bitbucket --stacktrace --info
           after-script:
             - pipe: atlassian/checkstyle-report:0.2.0
           artifacts: 
             - osk-flows/build/reports/tests/**
             - koderia-flows/build/reports/tests/**
             - functions/build/reports/tests/**
     - build-jar: &build-jar
       - step:
           name: Build FAT Jar
           caches:
            - gradle
            - maven
           script:
             - gradle build -x test --stacktrace --info   
           artifacts:
             - osk-flows/dist/**
             - koderia-flows/dist/**
     - deploy-2-gcr: &deploy-2-gcr
         - step:
             name: Deploy Docker Image
             image: gcr.io/cloud-builders/gcloud
             caches:
               - gradle
               - maven
             script:
               - export PROJECT_ID=objectify-infra
               - gcloud auth activate-service-account --key-file koderia-flows/gcr/gcr-push-sa-key.json
               - gcloud config set project $PROJECT_ID
               - cp -a koderia-flows/dist/ koderia-flows/docker/
               - cd koderia-flows/docker/
               - chown -R 1000:1000 .
               - gcloud builds submit .
               - rm -rf dist/
     - deploy-snaphost-2-BB: &deploy-2-BB
       - step: 
           name: Deploy snapshot to Bitbucket downloads
           script:
             - pipe: atlassian/bitbucket-upload-file:0.3.2
               variables:
                 BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                 BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                 FILENAME: "osk-flows/dist/*.jar"
   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'



pipelines:
  branches: 
    develop:
      - <<: *run-tests
    master:
      - <<: *run-tests
    release/*:
      - <<: *run-tests
      - <<: *build-jar
      - <<: *deploy-2-gcr
      - <<: *deploy-2-BB
  tags:
    v*:
      - <<: *build-jar
      - <<: *deploy-2-gcr
      - <<: *deploy-2-BB