image: gradle:6.8.2

definitions: 
   steps:
     - step: &test
         name: 'Run tests'
         script:
           - gradle test -Dspring.profiles.active=bitbucket --stacktrace --info
         services:
           - postgres
         artifacts:
           - ./**/build/reports/tests/test/**

     - step: &mirror-to-github
         name: 'Mirror push to git@github.com:com-obj/notiflow.git'
         script:
           - git push --mirror git@github.com:com-obj/notiflow.git

   services: 
     postgres: 
       image: postgres 
       variables: 
         POSTGRES_DB: 'nc' 
         POSTGRES_USER: 'nc'
         POSTGRES_PASSWORD: 'ZMss4o9mdBLV'

clone:
  depth: full

pipelines:
  branches:
    develop:
      - step: *test
      - step: *mirror-to-github
