site_name: Notiflow
theme:
  name: material
  features:
    - content.code.annotate

# Copyright
copyright: Copyright &copy; 2021 - 2021 Objectify, s.r.o.

# Page tree
nav:
  - Fundamentals: index.md
  - Features: features.md
  - Getting started:
    - Installation: getting-started.md
    - Guides: examples.md
  - Architecture and design:
    - Flows: flows.md
    - Functions: functions.md
    - Payloads: entities.md
  - Web UI: web-ui.md
  - Releases:
    - Changelog: changelog.md
  - License: license.md
  #- API Reference: api.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.snippets  
  - admonition