version: '3'


services:

  postgres:
    image: postgres:10
    container_name: nc-postgres
    restart: always
    environment:
      POSTGRES_DB: nc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 25432:5432

