@startuml

!theme cerulean-outline

left to right direction

skinparam backgroundcolor White
skinparam component {
    backgroundColor<<user defined>> LightGray
}


database "Topic/Channels" {
    component MAILCHIMP_PROCESSING_FLOW_ID_INPUT<<PUB/SUB>>[
        MAILCHIMP_PROCESSING_FLOW_ID_INPUT
        --
        (MailchimpMessage)
    ]
    
    component DELIVERY_INFO_SEND_FLOW_ID_INPUT<<PUB/SUB>>  [
        DELIVERY_INFO_SEND_FLOW_ID_INPUT
        --
        (HasReceivingEndpoints)
    ]
    
    component MAILCHIMP_PROCESSING_FLOW_ID_OUTPUT_CHANNEL_ID<<PUB/SUB>>[
        MAILCHIMP_PROCESSING_FLOW_ID_OUTPUT_CHANNEL_ID
        --
        (MailchimpMessage)
    ]

}

component "MessageProcessingFlow" {
    [endpointPersister]
    [messagePersister]
    [readTrackingDecorator]
    [mailchimpMessageSender]    

    endpointPersister -l-> messagePersister: (MailChimpMessage)
    messagePersister -l-> readTrackingDecorator: (MailChimpMessage)
    readTrackingDecorator -l-> mailchimpMessageSender: (MailChimpMessage)
    mailchimpMessageSender ..> DELIVERY_INFO_SEND_FLOW_ID_INPUT: (MailChimpMessage)
    mailchimpMessageSender ..> MAILCHIMP_PROCESSING_FLOW_ID_OUTPUT_CHANNEL_ID: (MailChimpMessage)
    endpointPersister ..> MAILCHIMP_PROCESSING_FLOW_ID_INPUT : (MailChimpMessage) 
    
    note left of readTrackingDecorator 
        if (nc.functions.tracking.enabled = true 
            AND contentType = MediaType.TEXT_HTML_VALUE)
            do
        else
            skip      
    end note 

}


@enduml