@startuml

!theme cerulean-outline

left to right direction

skinparam backgroundcolor White
skinparam component {
    backgroundColor<<user defined>> LightGray
}

database "PostgreSQL" {
    [nc_message]
    [nc_endpoint]
}

database "Topic/Channels" {
    component SMS_PROCESSING_FLOW_ID_INPUT<<PUB/SUB>>[
        SMS_PROCESSING_FLOW_ID_INPUT
        --
        (Message)
    ]

    component DELIVERY_INFO_SEND_FLOW_ID_INPUT<<PUB/SUB>>  [
        DELIVERY_INFO_SEND_FLOW_ID_INPUT
        --
        (HasRecievingEndpoints)
    ]

}

component "MessageProcessingFlow" {
    [smsFormatter]
    [splitter]
    [endpointPersister]
    [messagePersister]
    [smsSender]

    smsFormatter -l-> splitter : (Message<SimpleTextContent>)
    splitter -l-> endpointPersister : (Message<SimpleTextContent>)
    endpointPersister -l-> messagePersister: (Message<SimpleTextContent>)
    messagePersister -l--> smsSender: (Message<SimpleTextContent>)

    smsFormatter ..> SMS_PROCESSING_FLOW_ID_INPUT : (Message<TemplateWithModelContent>) 

    messagePersister -u-> nc_message: (List<DeliveryInfo>)
    endpointPersister -u-> nc_endpoint: (List<RecievingEndpoint>)

    smsSender ..> DELIVERY_INFO_SEND_FLOW_ID_INPUT : (Message<TemplateWithModelContent>) 

}


@enduml