spring.datasource:
   platform: postgres
   url: jdbc:postgresql://localhost:25432/nc
   username: nc
   password: ZMss4o9mdBLV

spring.mail:
   host: localhost
   port: 3025
   username: no-reply@objectify.sk
   password: xxx

nc.functions.event-generator:
   source-dir: ${user.home}/eventsQueue

nc.functions.send-email-message.from: no-reply@objectify.sk

osk.sia.impact-notif:
#   ico-of-la-custumers-to-be-notified:
#      - 00686930 #Tatrabanka a.s.
#      - 00151866 #Ministerstvo vnútra SR
   b2b-login-of-la-custumers-to-be-notified:
      - Tatrabanka
      - MVSR
   
