spring.datasource:
   platform: postgres
   url: jdbc:postgresql://localhost:25432/nc
   username: nc
   password: ZMss4o9mdBLV

spring.mail:
   host: localhost
   port: 3025
   username: no-reply@objectify.sk
   password: xxx

nc.functions:
   event-generator:
      source-dir: ${user.home}/eventsQueue    
   send-email-message:
      from: no-reply@objectify.sk  
   email-templates:
      templates-root-dir: src/main/resources/templates
      messages-dir-and-base-name: src/main/resources/templates/messages

osk.sia.functions.impact-notif-converter:
   b2b-login-of-la-custumers-to-be-notified:
      - Tatrabanka
      - MVSR
   cs-agents-to-notify-email:
      - sales.agent@orange.sk
      
      
testmode:
   enabled: false
   smtp:
      host: localhost
      port: 3025
      username: cuzy@objectify.sk
      password: xxx
      recipient: cuzy@objectify.sk
      periodMinutes: 1
      
testmode:
   enabled: false
   smtp:
      host: localhost
      port: 3025
      username: testmode_no-reply@objectify.sk # this has to be different to spring.mail.username, for more info see TestmodeIntegrationTests
      password: xxx
      recipients: 
         - cuzy@objectify.sk
      periodMinutes: 1
   
#logging.level:
#   org.springframework.beans: DEBUG
