spring:
   cloud.gcp:
      sql.enabled: false
      core.enabled: false
   datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:25432/nc
      username: nc
      password: ZMss4o9mdBLV
   mail:
      host: smtp.office365.com
      port: 587
      username: no-reply@objectify.sk
      password: Bos16428
      protocol: smtp
      default-encoding: UTF-8
      properties:
         mail.smtp.auth: true
         mail.smtp.starttls.enable: true

nc:
   functions:
      event-generator:
         source-dir: ${user.home}/eventsQueue    
      send-email-message:
         from: no-reply@objectify.sk  
      email-templates:
         templates-root-dir: 
            - src/main/resources/message-templates
         messages-dir-and-base-name: file:src/main/resources/message-templates/messages
   flows:    
      input-evet-routing:
         type: PAYLOAD_TYPE
         type-channel-mapping:
            OUTAGE_START: OUTAGE_START_INPUT
            OUTAGE_END: OUTAGE_END_INPUT

osk.sia.functions:
   impact-notif-converter:
      b2b-login-of-la-custumers-to-be-notified:
         - Tatrabanka
         - MVSR
      cs-agents-to-notify-email:
         - sales@objectify.skk
   sms-sender:
      gap-api-url: http://localhost:6090/API/smsmessaging/v1
      gap-api-login: testlogin
      gap-api-password: testpw
      client-correlator-prefix: nc
#      notify-url: http://localhost:8080/smssender
      sender-address: 3333
      bill-code: WZ00

   
#logging.level:
#   org.springframework.beans: DEBUG


#debug: true

---
spring.config.activate.on-profile: test_mode
      
nc:
   flows:
      test-mode:
         enabled: true
         recipients: 
            - cuzy@objectify.sk

---