spring.cloud.gcp:
   project-id: test-osk-notifications
   credentials.location: file:src/main/resources/test-osk-notifications-key.json
   sql:
      enabled: true
      instance-connection-name: test-osk-notifications:europe-west1:test-osk-notif-db
      database-name: nc
   core:
      enabled: true

spring.datasource:
   platform: postgres
   username: postgres
   password: A3r5dxRDv7edZXE6
#   initialization-mode: always
   url: jdbc:postgresql://google/${spring.cloud.gcp.sql.database-name}?cloudSqlInstance=${spring.cloud.gcp.sql.instance-connection-name}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${spring.datasource.username}&password=${spring.datasource.password}


spring.mail:
  host: smtp.office365.com
  port: 587
  username: no-reply@objectify.sk
  password: Bos16428
  protocol: smtp
  default-encoding: UTF-8
  smtp:
    auth: true
    starttls: true
      
testmode:
   enabled: true
   
osk.sia.functions.impact-notif-converter:
   b2b-login-of-la-custumers-to-be-notified:
      - Tatrabanka
      - MVSR
   cs-agents-to-notify-email:
      - cuzy@objectify.sk
  
#logging.level:
#   org.springframework.beans: DEBUG
