apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "koderia-flows.fullname" . }}
  labels:
{{ include "koderia-flows.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "koderia-flows.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "koderia-flows.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RELEASE_NAME
            value: {{ include "koderia-flows.fullname" . }}
          - name: SPRING_PROFILES_ACTIVE
            value: {{ include "koderia-flows.activeProfiles" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "koderia-flows.fullname" . }}-config-volume
              mountPath: /var/{{ include "koderia-flows.fullname" . }}-config/
              readOnly: true
      volumes:
        - name: {{ include "koderia-flows.fullname" . }}-config-volume
          configMap:
            name: {{ include "koderia-flows.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
