version: '3'

services:
  nc-postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: nc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 25432:5432
      
  rabbitmq:
    image: rabbitmq:3.7-management
    expose:
      - '5672'
      - '15672'
    ports:
      - 5672:5672
      - 15672:15672
