@startuml
!theme cerulean-outline

skinparam backgroundcolor White
skinparam component {
    BackgroundColor<<user defined>> LightGray
    BorderColor<<user defined>> Gray
    FontColor<<user defined>> Black

    FontColor DarkSlateGray
    FontName Courier
    FontSize 15

}

component appWithContacts [
    your-app-with-contacts
] 

component [your-app] {

    [you-service]

    component [noti-flow] {

        () "Java API" as javaApi

        package flows {
            component customFlow [
                main-custom-flow
            ] 
        }

        package functions {
            component persistMessage [
                F1
            ] 

            component sendEmail [
                F2
            ] 

            component customFunction<<user defined>> [
                calculate-recipients
            ] 
        }


    }

    [you-service] -> javaApi: call
    javaApi --> customFlow: call

    customFlow .. persistMessage: consists of
    customFlow .. sendEmail: consists of
    customFlow .. customFunction: consists of
}
 
customFunction --> appWithContacts: call

@enduml