apiVersion: v1
kind: Pod
spec:
  containers:
    - name: gradle
      image: gradle:6.8.1-jdk8
      imagePullPolicy: IfNotPresent
      command:
        - cat
      tty: true
      lifecycle:
        postStart:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo \"org.gradle.jvmargs=-Xmx4g\norg.gradle.daemon=false\" > /root/.gradle/gradle.properties"
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"

    - name: gcloud
      image: gcr.io/cloud-builders/gcloud
      command:
        - cat
      tty: true
      env:
        - name: LANG
          value: C.UTF-8
        - name: LC_ALL
          value: C.UTF-8

    - name: helm
      image: alpine/helm:2.14.2
      command:
        - cat
      tty: true

    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      command:
        - cat
      tty: true

    - name: postgres
      image: postgres:10
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: nc
        - name: POSTGRES_PASSWORD
          value: ZMss4o9mdBLV
        - name: POSTGRES_DB
          value: nc
      resources:
        requests:
          memory: "1Gi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: worker
                operator: In
                values:
                  - jenkins
  tolerations:
    - key: worker
      operator: Equal
      value: jenkins
      effect: NoSchedule
