
spring.cloud:
   function:
      definition: generateEvent;validateAndGenerateEventId;persistPIForEvent;resolveRecipients;persistPIForEventWithRecipients;generateMessagesFromEvent;persistPIForMessage;sendMessage;logEvent
   
   stream:
      bindings:
         generateEvent-out-0:
            destination: ext_event
            producer.requiredGroups: ext_event-processing-group
            
         validateAndGenerateEventId-in-0:
            destination: ext_event
            group: ext_event-processing-group
         validateAndGenerateEventId-out-0:
            destination: event
            producer.requiredGroups: event-processing-group,event-persisting-group
            
         persistPIForEvent-in-0:
            destination: event
            group: event-persisting-group
            
         resolveRecipients-in-0:
            destination: event
            group: event-processing-group
         resolveRecipients-out-0:
            destination: event-with-settings
            producer.requiredGroups: event-settings-consumer,event-persisting-group2
            
         persistPIForEventWithRecipients-in-0:
            destination: event-with-settings
            group: event-persisting-group2
            
         generateMessagesFromEvent-in-0:
            destination: event-with-settings
            group: event-settings-consumer
         generateMessagesFromEvent-out-0:
            destination: message
            producer.requiredGroups: message-consumer,message-persisting-group,message-sender
            
         persistPIForMessage-in-0:
            destination: message
            group: message-persisting-group
            
         sendMessage-in-0:
            destination: message
            group: message-sender
            
         logEvent-in-0:
            destination: message
            group: message-consumer
            
      poller.fixedDelay: "1000"

spring.datasource:
   platform: postgres
   url: jdbc:postgresql://localhost:25432/nc
   username: root
   password: rootpw
   
spring.mail:
   host: smtp.office365.com
   port: 587
   username:  no-reply@objectify.sk
   password: <login password to smtp server>
   properties.mail.smtp:
      auth: true
      starttls.enable: true   

   
management.endpoints.web.exposure.include: '*'

functions.event-generator.sourceDir: src/test/resources/eventsQueue

