
spring.cloud:
   function:
      definition: generateEvent;generateProcessingId;persistPIForEvent;resolveRecipients;persistPIForEventWithRecipients;generateMessagesFromEvent;persistPIForMessage;logEvent
   
   stream:
      bindings:
         generateEvent-out-0:
            destination: ext_event
            producer.requiredGroups: ext_event-processing-group
            
         generateProcessingId-in-0:
            destination: ext_event
            group: ext_event-processing-group
         generateProcessingId-out-0:
            destination: event
            producer.requiredGroups: event-processing-group,event-persisting-group
            
         persistPIForEvent-in-0:
            destination: event
            group: event-persisting-group
            
         resolveRecipients-in-0:
            destination: event
            group: event-processing-group
         resolveRecipients-out-0:
            destination: event-with-settings
            producer.requiredGroups: event-settings-consumer,event-persisting-group2
            
         persistPIForEventWithRecipients-in-0:
            destination: event-with-settings
            group: event-persisting-group2
            
         persistPIForMessage-in-0:
            destination: event-with-settings
            group: event-settings-consumer
         generateMessagesFromEvent-out-0:
            destination: message
            producer.requiredGroups: message-consumer,event-persisting-group3
            
         persistPIWithMessages-in-0:
            destination: message
            group: event-persisting-group3
            
         logEvent-in-0:
            destination: message
            group: message-consumer
            
      poller.fixedDelay: "1000"

spring.datasource:
   platform: postgres
   url: jdbc:postgresql://localhost:25432/nc
   username: root
   password: rootpw
   
management.endpoints.web.exposure.include: '*'
functions.event-generator.sourceDir: src/test/resources/events

