spring.mail:
   host: localhost
   port: 3025
   username: no-reply@objectify.sk
   password: xxx

nc.functions.event-generator.sourceDir: ${user.home}/eventsQueue

nc:
   functions:
      event-generator:
         soruce-dir: ${user.home}/eventsQueue
   flows:
      test-mode:
         enabled: true
         periodInSeconds: 5