spring.mail:
   host: localhost
   port: 3025
   username: no-reply@objectify.sk
   password: xxx

testmode:
   enabled: true
   smtp:
      host: smtp.office365.com
      port: 587
      username: no-reply@objectify.sk
      password: Bos16428
      recipient: bazik@objectify.sk

nc.functions.event-generator.sourceDir: ${user.home}/eventsQueue

app:
   scheduling:
      enabled: true