spring.mail:
   host: localhost
   port: 3025
   username: no-reply@objectify.sk
   password: xxx

testmode:
   enabled: true
   smtp:
      host: localhost
      port: 3025
      username: no-reply@objectify.sk
      password: xxx
      recipient: testmode_recipient@objectify.sk
      periodMinutes: 5

nc.functions.event-generator.sourceDir: ${user.home}/eventsQueue