release.name: koderia-flows

spring.cloud:
   function:
      definition: emitKoderiaEvent;convertKoderiaEvent;validateAndGenerateEventId;persistPIForEvent;resolveRecipients;persistPIForEventWithRecipients;generateMessagesFromEvent;persistPIForMessage;sendMailchimpMessage;persistPIForSendMessage;logEvent

   stream:
      bindings:
         emitKoderiaEvent-out-0:
            destination: ext_event
            producer.requiredGroups: ext_event-processing-group

         convertKoderiaEvent-in-0:
            destination: ext_event
            group: ext_event-processing-group
         convertKoderiaEvent-out-0:
            destination: convert_event
            producer.requiredGroups: convert_event-processing-group

         validateAndGenerateEventId-in-0:
            destination: convert_event
            group: convert_event-processing-group
         validateAndGenerateEventId-out-0:
            destination: event
            producer.requiredGroups: event-processing-group,event-persisting-group

         persistPIForEvent-in-0:
            destination: event
            group: event-persisting-group

         resolveRecipients-in-0:
            destination: event
            group: event-processing-group
         resolveRecipients-out-0:
            destination: event-with-settings
            producer.requiredGroups: event-settings-consumer,event-persisting-group2

         persistPIForEventWithRecipients-in-0:
            destination: event-with-settings
            group: event-persisting-group2

         generateMessagesFromEvent-in-0:
            destination: event-with-settings
            group: event-settings-consumer
         generateMessagesFromEvent-out-0:
            destination: message
            producer.requiredGroups: message-persisting-group,message-sender

         persistPIForMessage-in-0:
            destination: message
            group: message-persisting-group

         sendMailchimpMessage-in-0:
            destination: message
            group: message-sender
         sendMailchimpMessage-out-0:
            destination: send-message
            producer.requiredGroups: send-message-persisting-group,message-logger

         persistPIForSendMessage-in-0:
            destination: send-message
            group: send-message-persisting-group

         logEvent-in-0:
            destination: send-message
            group: message-logger

      poller.fixedDelay: "1000"

spring.datasource:
   platform: postgres
   url: jdbc:postgresql://localhost:25432/nc
   username: nc
   password: ZMss4o9mdBLV

spring.mail:
   host: localhost
   port: 3025
   username: no-reply@localhost
   password: xxx

management.endpoints.web.exposure.include: '*'

koderia.api.uri: https://www.koderia.sk/api/v1

mailchimp:
   api:
      key: MOCKkey
      uri: http://mandrillapp.com/api/1.0
      from-name: Koderia sender
      from-email: sender@koderia.sk
   template:
      aggregate-subject: Koderia digest
      aggregate-name: aggregate-template
      job-post-name: job-post-template
      blog-name: blog-template
      event-name: event-template
      link-name: link-template
      news-name: news-template
