release.name: koderia-flows

spring:
   mail:
      host: localhost
      port: 3025
      username: no-reply@objectify.sk
      password: xxx
   datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:25432/nc
      username: nc
      password: ZMss4o9mdBLV
   main.allow-bean-definition-overriding: true

management.endpoints.web.exposure.include: '*'

nc:
   functions:
      email-sender:
         from-mail-address: no-reply@objectify.sk
   flows:
      input-evet-routing:
         type: FLOW_ID

koderia.functions:
   recipients-finder:
      koderia-api-url: https://us-central1-koderia-develop.cloudfunctions.net/apiExternal
      koderia-api-token: fbtYmk5vXY9hlCKX5abBfuDhKjcY5IFQXbomVA6Uxv6CUi8gXsaruWXCA4hWPgygIx49F6Dfgk6B0sE65AytH9YXvBzKKrw2Xm0WYaWr73ZpMpDhFlaBbo1ufM5c6a81WCqKUHyIjf6ez11GqEzHHFG8v7GRMKhBGJe9zjOYMFWZ1ZBD3eEuQPal9sgsP5cWVsTZV32ls0BrWU9EkYcwwsxFXEeD3PKAyFx6Bzp4rPNsgU5f8fYgTmjynyAPaZ6p
   mailchimp-sender:
      aggregate-subject: Koderia digest
      mailchimp-api:
         url: http://mandrillapp.com/api/1.0
         auth-key: MOCKkey
         sender-name: Koderia sender
         sender-email: sender@koderia.sk
      mailchimp-template-names:
         aggregate: aggregate-template
         job-post: job-post-template
         blog: blog-template
         event: event-template
         link: link-template
         news: news-template

---
spring.config.activate.on-profile: test_mode

nc.flows.test-mode:
   enabled: true
   recipients:
      - bazik@objectify.sk