# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

on:
  push:
    branches:
      - master
      - 'release/*'
      - 'hotfix/*'
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11.9
        env:
          POSTGRES_DB: nc
          POSTGRES_USER: nc
          POSTGRES_PASSWORD: ZMss4o9mdBLV
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 25432:5432
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Publish to Maven Central
        run: |
          ./gradlew \
            -P sonatypeUsername=${{ secrets.SONATYPE_USERNAME }} \
            -P sonatypePassword=${{ secrets.SONATYPE_PASSWORD }} \
            -P gpgSigningKey=${{ secrets.GPG_SIGNING_KEY }} \
            -P gpgSigningPassword=${{ secrets.GPG_SIGNING_PASSWORD }} \
            publishToSonatype \
            closeAndReleaseSonatypeStagingRepository
